# Zsh History #
export ZSH_CONFIG="$HOME/.config/zsh/"
HISTFILE="$ZSH_CONFIG/.zshstory"
HISTSIZE=10000000
SAVEHIST=10000000

autoload -Uz compinit && compinit
# Brick Env #
export EDITOR="/usr/local/bin/lvim"
export ACLOCAL_FLAGS="-I/opt/local/share/aclocal $ACLOCAL_FLAGS"
export LD_LIBRARY_PATH=/opt/local/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/opt/local/lib:$DYLD_LIBRARY_PATH

# export RISCV=/opt/riscv
# export MANPATH=/opt/local/man:$MANPATH

# Spicetify
# export SPICETIFY_INSTALL="/home/brick/spicetify-cli"

# SST 
# export SST_CORE_HOME=$HOME/local-brick/sst/sstcore-10.1.0
# export SST_CORE_ROOT=$HOME/build-brick/sst/sstcore-10.1.0
# export PMIX_MCA_gds=hash

# Brick Path
path+=$HOME/.local/bin
path+=$HOME/.local/opt/llvm/bin
path+=$HOME/brick/.cargo/bin
path+=/opt/local/sbin
path+=/opt/local/bin
path+=/usr/local/opt/llvm/bin
path+=/opt/riscv/bin
path+=/Library
path+=/usr/sbin
export PATH

export PATH=$HOME/.config/nvcode/utils/bin:$PATH
export PATH="$HOME/.local/opt/llvm/bin:$PATH"


# export PATH="#/usr/local/java/jre1.8.0_281/bin:$PATH"

# Custom Brick Functions
source ~/BrickDot/BrickFunctions.sh
# Alias vim -> nvim
if type nvim > /dev/null 2>&1; then
  alias vim='lvim'
fi
alias vi="vim"

antibody bundle < ~/.brick-zsh.txt > ~/.brick-zsh.sh 
source ~/.brick-zsh.sh


# Autocomplete settings 
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=1
# zstyle ':completion:*:complete:*:' group-order \
  # options arguments values history-words local-directories files builtins 
### ALIASES ###
alias mkbld='mkdir build && cd build'
alias szrc='source ~/.zshrc'
alias cb=clipboard
export ANTIBODY_HOME=~/.antibody/

# 0 -- vanilla completion (abc => abc)
# 1 -- smart case completion (abc => Abc)
# 2 -- word flex completion (abc => A-big-Car)
# 3 -- full flex completion (abc => ABraCadabra)
zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'

alias ydl=youtube-dl
export TERM=xterm-256color
# export VIMINIT='source $MYVIMRC'
#compdef _gh gh

export NVPLUGS=$NVDIR/vim-plug/plugins.vim
alias cat=bat
if [ -e /home/brick/.nix-profile/etc/profile.d/nix.sh ]; then . /home/brick/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
alias kt='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'


#  Autosuggestion Complete on <tab> 
# bindkey '^E' end-of-line

eval "$(starship init zsh)"

# Setup command-not-found handler for Homebrew
HB_CNF_HANDLER="$(brew --repository)/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
source "$HB_CNF_HANDLER";
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
KOKKOS_PATH=/Users/brick/.src/kokkos
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
